### ISSUE TITLE
Extending this to IOU

### ISSUE THREAD

**Issue by mahima-manik** [corda/cordapp-template-kotlin#36]
I'm new to corda and tried following along [this](https://docs.corda.net/hello-world-template.html) step-by-step tutorial. After I run my nodes, I want to create some IOU.
When I run:
`start IOUFlow iouValue: 99, otherParty: "O=PartyB,L=New York,C=US"`

it is giving me the following error:
`No matching flow found, run 'flow list' to see your options.
`
And below is my flow list: 
```
net.corda.core.flows.ContractUpgradeFlow$Authorise
net.corda.core.flows.ContractUpgradeFlow$Deauthorise
net.corda.core.flows.ContractUpgradeFlow$Initiate
net.corda.finance.flows.CashConfigDataFlow
net.corda.finance.flows.CashExitFlow
net.corda.finance.flows.CashIssueAndPaymentFlow
net.corda.finance.flows.CashIssueFlow
net.corda.finance.flows.CashPaymentFlow
```
Also, I tried running:
`run vaultQuery contractStateType: com.template.IOUState
`
Error is:
```
Could not parse as a command: Cannot construct instance of `java.lang.Class`, problem: com.template.IOUState
 at [Source: UNKNOWN; line: -1, column: -1]
```

Where am I going wrong? 
Thank you

**Comment by launchsandy** [comment]
I guess you are using the Hello world example and not the suggested template. If that is the case, use the below

start com.example.flow.ExampleFlow$Initiator iouValue: 99, otherParty: "O=PartyB,L=New York,C=US"

run vaultQuery contractStateType: com.example.flow.ExampleFlow$Initiator

**Comment by nitinkaushik1910** [comment]
I was getting same error. Try -> run vaultQuery contractStateType: com.template.states.IOUState

**Comment by katrannakhla** [comment]
i have faced this error when run 
start IOUFLOW iouValue: 120, otherParty: "O=PartyB,L=New York,C=US"

proxies.ExceptionSerialisingRpcOpsProxy.log - Error during RPC invocation [errorCode=1t7f3c9, moreInformationAt=https://errors.corda.net/OS/4.0/1t7f3c9] {actor_id=internalShell, actor_owning_identity=O=PartyA, L=London, C=GB, actor_store_id=NODE_CONFIG, fiber-id=10000002, flow-id=03c6da62-83cf-467f-866d-b06716a7cde2, invocation_id=1b6ed0d1-3765-4055-9b63-83d701060935, invocation_timestamp=2019-03-12T18:24:44.963Z, origin=internalShell, session_id=e7787152-785d-47fc-a5a6-e8893a730942, session_timestamp=2019-03-12T18:14:02.935Z, thread-id=221, tx_id=35EF91102F2867F25C6D7C82C9BC363DC35BA87B217A9DC3E23C6A4E6EF8D150}

**Comment by goodstemy** [comment]
@nitinkausuhik worked for me thanks! 👏

**Comment by ianyepan** [comment]
`run vaultQuery contractStateType: com.template.states.IOUState` solved my `Could not parse as a command: Cannot construct instance of `java.lang.Class`, problem: com.template.IOUState
 at [Source: UNKNOWN; line: -1, column: -1]`

**Comment by joseph-jomon** [comment]
Hey guys have any one of you done a cordapp with updation of state ,cus , i am getting an  error while running the update command from the node, Error during RPC invocation
