### ISSUE TITLE
Circular dependency on gradle build

### ISSUE THREAD

**Issue by leric** [corda/cordapp-template-kotlin#41]
I'm following the instructions in readme, clone the repo, on branch release-V3, run ./gradlew buildNodes, and got this error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Circular dependency between the following tasks:
:classes
\--- :compileJava
     +--- :compileKotlin
     |    \--- :jar
     |         +--- :classes (*)
     |         \--- :compileKotlin (*)
     \--- :jar (*)

(*) - details omitted (listed previously)

```
Had the ~/.gradle folder cleaned, running on JDK 1.8.0_181，MacOS 10.13.6

Thanks

**Comment by leric** [comment]
I loved "cordapp" so much that I named the project "cordapp", the name conflict caused circular dependency, never mind

**Comment by bersling** [comment]
@leric  How did you figure that out from the error message? We have basically exactly the same error:
```
:lap:server:classes
\--- :lap:server:compileJava
     +--- :lap:server:compileKotlin
     |    \--- :lap:server:jar
     |         +--- :lap:server:classes (*)
     |         +--- :lap:server:compileKotlin (*)
     |         \--- :lap:server:inspectClassesForKotlinIC
     |              \--- :lap:server:classes (*)
     \--- :lap:server:jar (*)
```
but our root project has a pretty unique name.

Also, the issue didn't exist with Gradle 4, but it does with Gradle 5.
